### ISSUE TITLE
Uncaught TypeError: Cannot read property 'removeLineOffsets' of null

### ISSUE THREAD

**Issue by kjr247** [mupchrch/split-diff#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package, v0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'removeLineOffsets' of null

```
At /C:/Users/KRebstock/.atom/packages/split-diff/lib/split-diff.coffee:128

TypeError: Cannot read property 'removeLineOffsets' of null
  at Object.module.exports.SplitDiff.clearDiff (C:\Users\KRebstock\.atom\packages\split-diff\lib\split-diff.coffee:111:23)
  at Object.module.exports.SplitDiff.updateDiff (C:\Users\KRebstock\.atom\packages\split-diff\lib\split-diff.coffee:85:6)
  at C:\Users\KRebstock\.atom\packages\split-diff\lib\split-diff.coffee:69:8
  at Emitter.module.exports.Emitter.emit (C:\Users\KRebstock\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\KRebstock\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1273:25

```

### Commands

```
     -0:48.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:48.5.0 split-diff:disable (atom-text-editor.editor)
     -0:39.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:35.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:35.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:34.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:34.9.0 split-diff:disable (atom-text-editor.editor)
     -0:29.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:29.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:23.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:23.1.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:21.5.0 core:undo (atom-text-editor.editor.is-focused)
     -0:13.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:04.4.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:03.4.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
emmet, v2.3.13
split-diff, v0.4.0

# Dev
No dev packages
```

**Comment by mupchrch** [comment]
Please let me know if there is any other weirdness with the package trying to reactivate after disabling. I am still worried there might be edge cases I am missing.

**Comment by kjr247** [comment]
I just started using Atom yesterday and I am in love with it especially because of your package and a few others like it. So far the issue doesn't happen too often and if I either close those two files or restart atom, then the problem stops until it starts again.

**Comment by mupchrch** [comment]
Glad you like it! Just want to be clear, is this still happening after the update I pushed out a few days ago?

**Comment by kjr247** [comment]
I will update and get back to you.
