### ISSUE TITLE
Uncaught TypeError: Cannot read property 'softTabs' of undefined

### ISSUE THREAD

**Issue by it-praktyk** [mupchrch/split-diff#10]
[Enter steps to reproduce below:]

1. Two files to compare are opened - and only these two files
2. Select Packages -> Split-Diff -> Diff Panes

**Atom Version**: 0.186.0
**System**: linux 4.2.8-200.fc22.x86_64
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package, v0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'softTabs' of undefined

```
At /usr/share/atom/resources/app/src/text-editor.js:77

TypeError: Cannot read property 'softTabs' of undefined
  at new TextEditor (/usr/share/atom/resources/app/src/text-editor.js:77:27)
  at Object.module.exports.SplitDiff.getVisibleEditors (/home/wojtek/.atom/packages/split-diff/lib/split-diff.coffee:57:21)
  at Object.module.exports.SplitDiff.diffPanes (/home/wojtek/.atom/packages/split-diff/lib/split-diff.coffee:72:16)
  at atom-workspace.subscriptions.add.atom.commands.add.split-diff:diffPanes (/home/wojtek/.atom/packages/split-diff/lib/split-diff.coffee:22:35)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:75:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
 15x -4:22.0 core:backspace (atom-text-editor.editor.mini)
     -4:05.5 core:confirm (atom-text-editor.editor.mini)
 15x -1:34.2 core:select-left (atom-text-editor.editor.mini)
     -1:31.2 core:confirm (atom-text-editor.editor.mini)
     -0:21.3 split-diff:diffPanes (div.settings-view.pane-item)
     -0:11.9 core:cancel (div.settings-view.pane-item)
     -0:00.3 split-diff:diffPanes (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
language-powershell, v2.1.0
minimap-split-diff, v0.3.0
split-diff, v0.5.0

# Dev
No dev packages
```

**Comment by mupchrch** [comment]
I am not able to reproduce this with the steps you provided. Have you found any more specific ways to reproduce this issue?

**Comment by it-praktyk** [comment]
Today I've checked once again.

I've found that I've installed version atom-0.186.0-0.1.fc20.x86_64 on my Fedora 22. After upgrading Atom to atom-1.3.2-0.1.fc21.x86_64 (an rpm package downloaded from https://atom.io) your extension works fine.
