### ISSUE TITLE
Uncaught TypeError: atom.workspace.getCenter is not a function

### ISSUE THREAD

**Issue by codeitco** [mupchrch/split-diff#105]
[Enter steps to reproduce:]

1. Turn text wrapping off on each file in view
2. Run splitDiff

Error thrown immediately. Never experienced any split diff problems before until now and after most recent update.

hope this error log helps.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package 1.3.1

### Stack Trace

Uncaught TypeError: atom.workspace.getCenter is not a function

```
At C:\Users\Eric Bradshaw\.atom\packages\split-diff\lib\split-diff.coffee:296

TypeError: atom.workspace.getCenter is not a function
    at Object._getEditorsForQuickDiff (/packages/split-diff/lib/split-diff.coffee:296:28)
    at Object.diffPanes (/packages/split-diff/lib/split-diff.coffee:146:25)
    at Object.toggle (/packages/split-diff/lib/split-diff.coffee:58:8)
    at /packages/split-diff/lib/split-diff.coffee:46:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:109:21)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:70:7)
```

### Commands

```
     -2:13.8.0 core:save (input.hidden-input)
  2x -2:06.0 editor:toggle-soft-wrap (input.hidden-input)
     -1:56.3.0 split-diff:toggle (input.hidden-input)
  2x -1:39.3.0 intentions:highlight (input.hidden-input)
  2x -1:37.3.0 editor:toggle-soft-wrap (input.hidden-input)
     -1:35.8.0 split-diff:toggle (input.hidden-input)
     -1:13.1.0 intentions:highlight (input.hidden-input)
     -1:12.9.0 core:select-all (input.hidden-input)
     -1:12.3.0 core:copy (input.hidden-input)
     -0:54.8.0 intentions:highlight (input.hidden-input)
     -0:54.7.0 core:select-all (input.hidden-input)
     -0:54.5.0 intentions:highlight (input.hidden-input)
     -0:54.1.0 core:copy (input.hidden-input)
  2x -0:14.1.0 editor:toggle-soft-wrap (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
api-docs 0.0.6 
atom-autocomplete-php 0.22.2 
atom-bracket-highlight 0.3.2 
atom-cursor-indent 0.1.1 
atom-lorempixel 0.1.0 
atom-material-ui 1.3.10 
atom-minify 0.8.0 
atom-typescript 11.0.3 
auto-id-class 0.2.6 
auto-indent 0.5.0 
autoclose-html 0.23.0 
autocomplete-emojis 2.5.0 
autocomplete-paths 1.0.5 
autocomplete-php 0.3.7 
autoprefixer 3.6.1 
block-comment-plus 0.4.0 
bracket-close-jump 0.1.2 
busy 0.7.0 
busy-signal 1.4.1 
caniuse 0.9.0 
change-case 0.6.5 
chrome-color-picker 0.8.0 
color-picker 2.2.5 
css-spy 0.6.0 
custom-invisibles 0.1.2 
data-atom 0.25.0 
editor-background 1.2.38 
expose 0.14.0 
file-bookmark 1.0.3 
file-icons 2.1.4 
flex-tool-bar 0.12.0 
fonts 2.0.0 
git-plus 7.7.0 
glowing-cursor 0.1.2 
highlight-bad-chars 1.0.5 
highlight-line 0.12.0 
highlight-selected 0.13.1 
imdone-atom 2.2.5 
imdone-atom-github 0.1.11 
indent-guide-improved 1.4.12 
intentions 1.1.2 
isotope-ui 2.8.0 
jshint 1.8.6 
keybinding-cheatsheet 0.1.1 
language-aspx 0.5.0 
language-cshtml 0.2.1 
less-than-slash 0.16.0 
linter 2.1.4 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-jshint 3.0.3 
linter-php 1.3.2 
linter-sass-lint 1.7.4 
linter-scss-lint 3.1.0 
linter-ui-default 1.2.3 
lipsum 0.1.0 
livereload 0.4.4 
local-history 4.0.1 
minimap 4.27.1 
minimap-autohide 0.10.1 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
multirow-tabs 0.3.3 
nav-panel-plus 0.2.1 
open-in-browsers 0.0.19 
open-recent 5.0.0 
package-cop 0.2.10 
pdf-view 0.57.0 
php-cs-fixer 4.1.0 
pigments 0.39.1 
pretty-json 1.6.3 
project-manager 3.3.4 
project-viewer 1.0.13 
qolor 0.4.1 
quick-editor 0.4.3 
release-notes 0.53.0 
remote-sync 4.1.5 
seti-icons 1.4.3 
soft-wrap-indicator 1.0.1 
sort-lines 0.14.0 
split-diff 1.3.1 
svg-preview 0.11.0 
sync-settings 0.8.1 
tabs-to-spaces 1.0.3 
terminal-plus 0.14.5 
text-manipulation 0.6.0 
time-status 1.1.2 
todo-show 1.11.0 
toggle-gutter 0.3.3 
toggle-packages 1.1.0 
toggle-quotes 1.0.1 
tool-bar 1.1.0 
trailing-spaces 0.4.0 
tree-view-autoresize 1.6.0 
tree-view-search-bar 0.1.3 
w3c-validation 0.4.0 
webbox-color 0.5.9 
wordcount 2.10.4 
xml-formatter 0.10.0 
```

**Comment by mupchrch** [comment]
@codeitco Hm did you happen to recently install/update split-diff manually?

The version of split-diff you have is 1.3.1 which is only supposed to be [available for atom v1.17 and higher](https://github.com/mupchrch/split-diff/blob/master/package.json#L36). You seem to have atom v1.16, so you shouldn't have received an option to update to 1.3.1 until after you received the upcoming atom update.

**Comment by codeitco** [comment]
Actually, I think you just figured it out for me!  I had atom beta
installed and then reinstalled overtop with the standard version because of
too many other bugs I was experiencing (not related to split-diff).

I'll just uninstall and reinstall spit diff and hopefully it will be ok
again.

Thanks!

**Comment by mupchrch** [comment]
Awesome! Let me know if that doesn't work out for you!

**Comment by onetimepassword** [comment]
Uncaught TypeError: atom.workspace.getCenter is not a function[Enter steps to reproduce:]

1. Split pane left, added some text on one side, added some text to compare in other pane
2. Toggled on split diff, cause exception
3. No did not do any manual installs, just recently did an update

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package 1.4.0


### Stack Trace

Uncaught TypeError: atom.workspace.getCenter is not a function

```
At /Users/stephan/.atom/packages/split-diff/lib/split-diff.coffee:339

TypeError: atom.workspace.getCenter is not a function
    at Object._getEditorsForQuickDiff (/packages/split-diff/lib/split-diff.coffee:339:28)
    at Object.diffPanes (/packages/split-diff/lib/split-diff.coffee:185:27)
    at Object.toggle (/packages/split-diff/lib/split-diff.coffee:90:8)
    at /packages/split-diff/lib/split-diff.coffee:78:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1179:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by mupchrch** [comment]
@onetimepassword I'm not sure what the actual problem is, but to get you back to safety, I think you could probably just uninstall split-diff and reinstall. Or you could update to atom 1.17.

Makes no sense though because split-diff v1.4.0 should never be allowed to be installed on anything less than atom 1.17...
