### ISSUE TITLE
Uncaught TypeError: Cannot read property 'oldLineStart' of undefined

### ISSUE THREAD

**Issue by pebie** [mupchrch/split-diff#12]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.5
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package, v0.5.2

### Stack Trace

Uncaught TypeError: Cannot read property 'oldLineStart' of undefined

```
At /Users/bouchez/.atom/packages/split-diff/lib/split-diff.coffee:167

TypeError: Cannot read property 'oldLineStart' of undefined
    at Object.module.exports.SplitDiff.selectDiffs (/Users/bouchez/.atom/packages/split-diff/lib/split-diff.coffee:167:19)
    at Object.module.exports.SplitDiff.nextDiff (/Users/bouchez/.atom/packages/split-diff/lib/split-diff.coffee:149:6)
    at atom-workspace.subscriptions.add.atom.commands.add.split-diff:nextDiff (/Users/bouchez/.atom/packages/split-diff/lib/split-diff.coffee:25:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  6x -4:17.7.0 core:undo (atom-text-editor.editor.is-focused)
  3x -4:13.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:11.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -4:11.2.0 git-diff-details:close-git-diff-details (atom-text-editor.editor.is-focused)
     -4:11.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -4:06.7.0 settings-view:open (atom-text-editor.editor.is-focused)
     -2:56.1.0 core:backspace (div.package-detail.panels-item)
     -1:04.3.0 core:undo (atom-text-editor.editor.is-focused)
     -0:52.2.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:48.5.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:48.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:48.3.0 git-diff-details:close-git-diff-details (atom-text-editor.editor.mini.is-focused)
     -0:48.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:44.8.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:11.1.0 split-diff:diffPanes (div.package-detail.panels-item)
     -0:03.5.0 split-diff:nextDiff (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "nuclide-code-format",
      "jsformat"
    ],
    "disabledPackages": [
      "linter-jscs",
      "linter-scss-lint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
atom-gdb, v0.4.0
atom-jshint, v2.0.0
behat-atom, v0.1.2
docblockr, v0.7.3
editorconfig, v1.2.0
git-diff-details, v0.21.0
jsdoc-generator, v0.1.10
language-babel, v1.0.0
linter, v1.7.2
linter-eslint, v5.2.6
php-twig, v4.0.0
project-manager, v2.6.1
react, v0.12.10
react-snippets, v0.2.0
split-diff, v0.5.2

# Dev
No dev packages
```

**Comment by mupchrch** [comment]
Fix on the way - I was not checking null when user is trying to use next/prev on diff with no differences.
