### ISSUE TITLE
Uncaught TypeError: Cannot read property 'copy' of undefined

### ISSUE THREAD

**Issue by zygimantus** [mupchrch/split-diff#124]
[Enter steps to reproduce:]

1. Split diff
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.4.16
**OS**: "Arch Linux"
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package 1.4.3

### Stack Trace

Uncaught TypeError: Cannot read property 'copy' of undefined

```
At /usr/lib/atom/src/text-editor.js:745

TypeError: Cannot read property 'copy' of undefined
    at TextEditor.module.exports.TextEditor.copy (/usr/lib/atom/src/text-editor.js:745:116)
    at Object._getEditorsForDiffWithActive (/packages/split-diff/lib/split-diff.coffee:402:37)
    at Object.diffPanes (/packages/split-diff/lib/split-diff.coffee:187:27)
    at /packages/split-diff/lib/split-diff.coffee:58:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:265:29)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/lib/atom/src/command-registry.js:166:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/lib/atom/src/atom-environment.js:1314:28)
    at EventEmitter.outerCallback (/usr/lib/atom/src/application-delegate.js:333:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:06.2.0 intentions:highlight (input.hidden-input)
     -1:05.6.0 find-and-replace:show (input.hidden-input)
     -1:04.5.0 editor:consolidate-selections (input.hidden-input)
     -1:04.5.0 core:cancel (input.hidden-input)
  2x -0:56.8.0 core:move-up (input.hidden-input)
     -0:19.7.0 split-diff:toggle (div.line.cursor-line)
     -0:09.5.0 pane:close (div.title)
     -0:02.1.0 split-diff:enable (div.title)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.30.4 
atom-material-syntax 1.0.6 
atom-maven 1.3.0 
busy-signal 1.4.3 
color-picker 2.2.5 
git-plus 7.9.3 
go-debug 1.5.0 
go-plus 5.5.5 
go-signature-statusbar 1.2.1 
intentions 1.1.2 
linter 2.2.0 
linter-ui-default 1.6.2 
minimap 4.28.3 
project-manager 3.3.5 
split-diff 1.4.3 
travis-ci-status 1.3.1 
```

**Comment by mupchrch** [comment]
Figured out steps to recreate the issue:
1. Toggle split diff on for a file so that it creates a right editor
2. Right click the untitled right editor's tab and click "Diff with Active File"
3. Notice error
