### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by BenLeggiero** [mupchrch/split-diff#128]
1. Scroll or click in editor while using SplitDiff

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2201

TypeError: Cannot read property 'id' of undefined
    at horizontalPositionsToMeasure.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2201:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2197:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:384:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:276:18)
    at TextEditorComponent.didMouseWheel (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1516:43)
```

### Commands

```
     -8:44.4.0 split-diff:toggle (input.hidden-input)
     -8:22.5.0 split-diff:ignore-whitespace (input.hidden-input)
  2x -8:12.1.0 core:copy (input.hidden-input)
     -7:01.8.0 split-diff:prev-diff (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax-dark.theme-atom-material-ui)
     -7:00.2.0 split-diff:next-diff (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax-dark.theme-atom-material-ui)
     -6:58.4.0 split-diff:prev-diff (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax-dark.theme-atom-material-ui)
```

### Non-Core Packages

```
atom-html-preview 0.1.22 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
atom-text-transformer 0.7.0 
autocomplete-swift 1.0.3 
drag-drop-text 0.1.4 
hex-editor 0.1.1 
highlight-selected 0.13.1 
language-applescript 0.3.0 
language-log 1.8.0 
language-markdown 0.25.1 
language-scala 1.1.9 
language-swift 0.5.0 
markdown-preview-plus 2.4.10 
markdown-writer 2.6.5 
minimap 4.29.6 
minimap-highlight-selected 4.6.1 
sort-lines 0.14.0 
split-diff 1.4.3 
Sublime-Style-Column-Selection 1.7.4 
transform 0.4.0 
```

**Comment by mupchrch** [comment]
Ok this is a weird one. I found a specific way to reproduce it like 50% of the time. Documenting it here so I won't forget.
1. In the `split-diff` git repo, have "split-diff.coffee" file open and visible.
2. Also have "README.md" open in another tab but not visible.
3. Right click "README.md" tab and choose "Diff with Active File".
4. Half of the time you will see the reported error.

I think this has to do with the editor rendering rewrite that was released with 1.19 but I need to figure out how to prove that.

**Comment by mupchrch** [comment]
@BenLeggiero Are you still seeing this issue? I just tried reproducing using my steps above and I am not seeing anything anymore...

**Comment by BenLeggiero** [comment]
Oh yeah this... I'll try again.

**Comment by BenLeggiero** [comment]
I can no longer reproduce this error. Seems fixed!

**Comment by mupchrch** [comment]
Thanks!
