### ISSUE TITLE
Cannot run split diff, missing 'space-pen'

### ISSUE THREAD

**Issue by BillXT** [mupchrch/split-diff#13]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package, v0.5.3

### Stack Trace

Failed to activate the split-diff package

```
At Cannot find module 'space-pen'

Error: Cannot find module 'space-pen'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (D:\Users\yannie.NET\AppData\Local\atom\app-1.4.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (D:\Users\yannie.NET\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/yannie/.atom/packages/split-diff-master/lib/split-diff.coffee:2:7)
    at Object.<anonymous> (file:///C:/Users/yannie/.atom/packages/split-diff-master/lib/split-diff.coffee:1:1)
    at Module._compile (D:\Users\yannie.NET\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (D:\Users\yannie.NET\AppData\Local\atom\app-1.4.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (D:\Users\yannie.NET\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (D:\Users\yannie.NET\AppData\Local\atom\app-1.4.0\resources\app.asar\src\package.js:721:27)
    at Package.module.exports.Package.activateNow (D:\Users\yannie.NET\AppData\Local\atom\app-1.4.0\resources\app.asar\src\package.js:173:16)
    at D:\Users\yannie.NET\AppData\Local\atom\app-1.4.0\resources\app.asar\src\package.js:801:25
    at Function.module.exports.Emitter.simpleDispatch (D:\Users\yannie.NET\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (D:\Users\yannie.NET\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (D:\Users\yannie.NET\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (D:\Users\yannie.NET\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (D:\Users\yannie.NET\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (D:\Users\yannie.NET\AppData\Local\atom\app-1.4.0\resources\app.asar\src\atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:29 split-diff:diffPanes (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai-slate"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-latex, v0.6.1
monokai-slate, v0.5.0

# Dev
No dev packages
```

I am trying to compare two Latex code I wrote. I am new to Atom and got this error.

**Comment by BillXT** [comment]
I installed https://github.com/atom/atom-space-pen-views and did the Package Update Dependencies. I don't get the error, but everything is marked as different.

**Comment by mupchrch** [comment]
Thanks for bringing the first issue to my attention. I will need to stop using space-pen, as it has been removed from core.

For the second issue, the only thing I can think of is that there is a difference in white space/hidden characters between the files. First, try going to Packages > Split Diff > Toggle Ignore Whitespace.

If that doesn't work, would it be possible to somehow upload the files so I can look at them, or at the very least paste the contents of each?

**Comment by BillXT** [comment]
Hello again,

Sorry for late reply, very busy here! Attached you can find the files. Hope you find the problem =)

**Comment by mupchrch** [comment]
I think you may have forgotten to attach the files :P

**Comment by BillXT** [comment]
I added them as a .zip file but it seems that it does not work, tried again several time and nothing. I changed the extension from .tex to .txt to be availble to upload them. You will have to change them back =)

**Comment by mupchrch** [comment]
Ah! Ok, so this is an annoying problem. It seems you have two different kinds of line endings between the files. In ch3.tex, you have each line separated by an EOL (end of line character). In ch3_old.tex, you have each line separated by a CR (carriage return character) and then an EOL.

I found this out by checking the "Show Invisibles" checkbox in the Atom settings. It will show you the characters that are in the document that you usually cannot see. I know that Windows likes to end lines differently than Linux/Mac, so that might explain how you got into this situation.

In the bottom right of the atom window, you will see something that says either "CRLF" or "LF". Make sure those match between the two files you are diffing.
