### ISSUE TITLE
"Computing the diff for you" - editor hangs

### ISSUE THREAD

**Issue by QuintinS** [mupchrch/split-diff#131]
I found split-diff to solve a problem I was having, since it seemed like the ideal tool.

I used as described... opened the file, ran "split diff: toggle"... but ally I get is a loading message saying "Computing the diff for you" which crashes the editor, necessitating a force-quit.

I've seen other issues with similar results dating back to 2016.

Atom: 1.19.2
Split-diff: 1.5.1

**Comment by mupchrch** [comment]
@QuintinS any chance you can reproduce with the console open? (ctrl+shift+p then search `dev tools`) Then if you run split-diff, does the console say anything? Does it happen on all files or specific files? Thanks

**Comment by ChrisRiddell** [comment]
@mupchrch I'm also seeing this issue.

I ran it with dev tools open and the only thing I see is this but that was there before running split diff

`IntersectionObserver.observe(target): target element is not a descendant of root.`

It's seems to only happen to me on large files eg I'm trying to diff a file that's 52,000 lines.

In task manager there is a atom process that's at 9.9% CPU and 700MB of RAM. the usage is only hitting one process on the 12 the system has (ryzen system).

I let it run on the "Computing the diff for you" for 45 mins then force quite atom.

Atom: 1.21.1
Split-diff: 1.5.1

**Comment by XaviLC** [comment]
I am experiencing the same issue but with split-diff 1.5.2

**Comment by WAFFO** [comment]
Hangs on finding the diff.

```
BufferedNodeProcess code was 1
split-diff.coffee? [sm]:326 module.js:545
    throw err;
    ^

Error: Cannot find module 'diff'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at _computeDiffChunks (/Users/ujs818/.atom/packages/split-diff-master/lib/compute-diff.js:22:16)
    at Object.<anonymous> (/Users/ujs818/.atom/packages/split-diff-master/lib/compute-diff.js:10:18)
    at Object.<anonymous> (/Users/ujs818/.atom/packages/split-diff-master/lib/compute-diff.js:193:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
```
