### ISSUE TITLE
Failed to load the split-diff package

### ISSUE THREAD

**Issue by franszo** [mupchrch/split-diff#134]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package 1.5.1

### Stack Trace

Failed to load the split-diff package

```
At error evaluating function `fade`: color.toHSL is not a function in /Users/jfrancovszky/.atom/packages/split-diff/styles/split-diff.less:13:26

LessError: error evaluating function `fade`: color.toHSL is not a function
  at /packages/split-diff/styles/split-diff.less:13:26
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-terminal 0.8.0 
auto-detect-indentation 1.3.0 
emmet 2.4.3 
highlight-selected 0.13.1 
language-babel 2.74.2 
language-pug 0.0.21 
minimap 4.29.7 
new-moon-atom-syntax 2.0.9 
open-terminal-here 2.3.1 
pane-layout-plus 0.7.3 
project-manager 3.3.5 
react-snippets 0.9.0 
split-diff 1.5.1 
```

**Comment by mupchrch** [comment]
@franszo Are you still seeing this issue?

**Comment by s-light** [comment]
i see it

[Enter steps to reproduce:]
1. open atom
2. error shown

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Ubuntu 17.10
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package 1.5.2


### Stack Trace

Failed to load the split-diff package

```
At EACCES: permission denied, open '/home/stefan/.atom/compile-cache/less/b5b3fa386a2f86e3092fa2ac8dfe679e286995c5/content/1f0e31f74a45e2a61d7f4e07749b178e87bde8ae/split-diff.json'

Error: EACCES: permission denied, open '/home/stefan/.atom/compile-cache/less/b5b3fa386a2f86e3092fa2ac8dfe679e286995c5/content/1f0e31f74a45e2a61d7f4e07749b178e87bde8ae/split-diff.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
    at Object.fs.writeFileSync (fs.js:1303:33)
    at Proxy.writeFileSync (/usr/share/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:298:29)
    at LessCache.module.exports.LessCache.writeJson (/usr/share/atom/resources/app/node_modules/less-cache/lib/less-cache.js:212:23)
    at LessCache.module.exports.LessCache.putCachedCss (/usr/share/atom/resources/app/node_modules/less-cache/lib/less-cache.js:300:18)
    at LessCache.module.exports.LessCache.cssForFile (/usr/share/atom/resources/app/node_modules/less-cache/lib/less-cache.js:358:18)
    at LessCompileCache.module.exports.LessCompileCache.cssForFile (/usr/share/atom/resources/app/src/less-compile-cache.js:43:31)
    at ThemeManager.loadLessStylesheet (/usr/share/atom/resources/app/src/theme-manager.js:282:37)
    at ThemeManager.loadStylesheet (/usr/share/atom/resources/app/src/theme-manager.js:248:25)
    at stylesheets.getStylesheetPaths.map.stylesheetPath (/usr/share/atom/resources/app/src/package.js:494:48)
    at Array.map (<anonymous>)
    at Package.loadStylesheets (/usr/share/atom/resources/app/src/package.js:493:56)
    at measure (/usr/share/atom/resources/app/src/package.js:135:20)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at Package.load (/usr/share/atom/resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/src/package-manager.js:618:16)
    at config.transact (/usr/share/atom/resources/app/src/package-manager.js:531:20)
    at Config.transact (/usr/share/atom/resources/app/src/config.js:819:20)
    at PackageManager.loadPackages (/usr/share/atom/resources/app/src/package-manager.js:529:23)
    at loadStatePromise.loadState.then (/usr/share/atom/resources/app/src/atom-environment.js:833:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
character-table 0.4.3 
copy-with-style 1.1.0 
editor-settings 1.1.3 
fold-functions 0.5.0 
hey-pane 1.1.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-arduino 0.4.3 
language-cython 0.3.0 
language-generic-config 1.4.0 
language-ini 1.20.0 
language-jison 2.11.0 
language-kconfig 0.2.0 
language-latex 1.1.1 
language-pcb 1.0.1 
language-restructuredtext 1.1.2 
language-svg 0.9.2 
linter 2.2.0 
linter-cpplint 2.0.1 
linter-eslint 8.4.1 
linter-flake8 2.3.0 
linter-gcc 0.7.1 
linter-gjslint 1.5.2 
linter-jsonlint 1.3.0 
linter-markdown 5.2.2 
linter-pylama 0.10.0 
linter-shellcheck 1.4.7 
linter-spell 0.15.0 
linter-spell-html 0.7.0 
linter-spell-javascript 0.9.0 
linter-spell-project 0.2.0 
linter-spell-shellscript 0.2.0 
linter-stylelint 4.3.0 
linter-tidy 2.3.1 
linter-ui-default 1.7.1 
linter-xmllint 1.4.4 
markdown-pdf 2.2.0 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
project-manager 3.3.6 
scroll-sync 0.2.4 
split-diff 1.5.2 
```

**Comment by s-light** [comment]
i just updated atom. and updated all packages.

and currently i get this:
```
Error loading Less stylesheet: /home/stefan/.atom/packages/split-diff/styles/split-diff.less

EACCES: permission denied, open '/home/stefan/.atom/compile-cache/less/b5b3fa386a2f86e3092fa2ac8dfe679e286995c5/content/1f0e31f74a45e2a61d7f4e07749b178e87bde8ae/split-diff.json'
```
and as second error message

> Failed to load the split-diff package

---
here the full error report.
[Enter steps to reproduce:]

1. just open atom

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Ubuntu 18.10
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package 1.5.4


### Stack Trace

Failed to load the split-diff package

```
At EACCES: permission denied, open '/home/stefan/.atom/compile-cache/less/b5b3fa386a2f86e3092fa2ac8dfe679e286995c5/content/1f0e31f74a45e2a61d7f4e07749b178e87bde8ae/split-diff.json'

Error: EACCES: permission denied, open '/home/stefan/.atom/compile-cache/less/b5b3fa386a2f86e3092fa2ac8dfe679e286995c5/content/1f0e31f74a45e2a61d7f4e07749b178e87bde8ae/split-diff.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.writeFileSync (fs.js:1303:33)
    at Proxy.writeFileSync (/usr/share/atom/resources/app/static/<embedded>:11:270631)
    at LessCache.t.exports.LessCache.writeJson (/usr/share/atom/resources/app/static/<embedded>:14:1064454)
    at LessCache.t.exports.LessCache.putCachedCss (/usr/share/atom/resources/app/static/<embedded>:14:1065937)
    at LessCache.t.exports.LessCache.cssForFile (/usr/share/atom/resources/app/static/<embedded>:14:1066913)
    at LessCompileCache.t.exports.LessCompileCache.cssForFile (/usr/share/atom/resources/app/static/<embedded>:14:13230)
    at ThemeManager.loadLessStylesheet (/usr/share/atom/resources/app/static/<embedded>:11:391265)
    at ThemeManager.loadStylesheet (/usr/share/atom/resources/app/static/<embedded>:11:390622)
    at stylesheets.getStylesheetPaths.map.e (/usr/share/atom/resources/app/static/<embedded>:11:2926399)
    at Array.map (<anonymous>)
    at Package.loadStylesheets (/usr/share/atom/resources/app/static/<embedded>:11:2926371)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:2919151)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:2918310)
    at Package.load (/usr/share/atom/resources/app/static/<embedded>:11:2919051)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/static/<embedded>:11:381323)
    at config.transact (/usr/share/atom/resources/app/static/<embedded>:11:379746)
    at Config.transact (/usr/share/atom/resources/app/static/<embedded>:11:332279)
    at PackageManager.loadPackages (/usr/share/atom/resources/app/static/<embedded>:11:379684)
    at t.loadState.then (/usr/share/atom/resources/app/static/<embedded>:1:659530)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-shell-commands 1.5.0 
busy-signal 2.0.0 
character-table 0.4.3 
circuitpython-force-to-drive 0.2.0 
copy-with-style 1.1.0 
editor-settings 1.1.3 
fold-functions 0.11.0 
hey-pane 1.1.2 
highlight-selected 0.14.0 
intentions 1.1.5 
language-arduino 0.4.3 
language-cython 0.3.0 
language-generic-config 1.4.0 
language-ini 1.20.0 
language-jison 2.12.0 
language-kconfig 0.2.0 
language-latex 1.2.0 
language-pcb 1.0.1 
language-restructuredtext 1.1.2 
language-svg 0.9.2 
linter 2.3.0 
linter-cpplint 2.0.1 
linter-eslint 8.5.0 
linter-flake8 2.4.0 
linter-gcc 0.7.1 
linter-gjslint 1.5.2 
linter-jsonlint 1.3.0 
linter-markdown 5.2.2 
linter-pylama 0.10.1 
linter-rst 0.0.3 
linter-shellcheck 1.6.0 
linter-spell 0.15.0 
linter-spell-html 0.7.0 
linter-spell-javascript 0.9.0 
linter-spell-project 0.2.0 
linter-spell-shellscript 0.2.0 
linter-stylelint 4.3.2 
linter-tidy 2.3.1 
linter-ui-default 1.7.1 
linter-xmllint 1.4.4 
markdown-pdf 2.2.0 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
process-palette 0.17.0 
project-manager 3.3.6 
scroll-sync 0.2.4 
split-diff 1.5.4 
```
