### ISSUE TITLE
Uncaught Error: Unable to watch path

### ISSUE THREAD

**Issue by jolebowski** [mupchrch/split-diff#140]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Debian GNU/Linux
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package 1.5.1

### Stack Trace

Uncaught Error: Unable to watch path

```
At /usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:95

Error: Unable to watch path
    at HandleWatcher.start (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:95:41)
    at new HandleWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:28:18)
    at new PathWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:148:36)
    at Object.exports.watch (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:242:18)
    at File.module.exports.File.subscribeToNativeChangeEvents (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:471:115)
    at File.module.exports.File.writeSync (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:386:20)
    at Object._createTempFiles (/packages/split-diff/lib/split-diff.coffee:503:21)
    at Object.updateDiff (/packages/split-diff/lib/split-diff.coffee:292:20)
    at /packages/split-diff/lib/split-diff.coffee:215:10
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1694:26)
    at later (/usr/share/atom/resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -0:37.2.0 autocomplete-plus:confirm (input.hidden-input)
  2x -0:36.7.0 core:move-right (input.hidden-input)
     -0:32.6.0 core:backspace (input.hidden-input)
  5x -0:25.4.0 core:move-down (input.hidden-input)
  2x -0:24.3.0 core:move-up (input.hidden-input)
     -0:22.2.0 intentions:highlight (input.hidden-input)
     -0:21.9.0 core:select-all (input.hidden-input)
     -0:21 command-palette:toggle (input.hidden-input)
     -0:17.9.0 editor:consolidate-selections (input.hidden-input)
     -0:17.9.0 core:cancel (input.hidden-input)
     -0:16.6.0 intentions:highlight (input.hidden-input)
     -0:15.9.0 split-diff:next-diff (input.hidden-input)
     -0:08.1.0 intentions:highlight (input.hidden-input)
     -0:07.6.0 core:copy (input.hidden-input)
     -0:06.8.0 intentions:highlight (input.hidden-input)
     -0:06.1.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.7 
autoclose-html 0.23.0 
autocomplete-paths 2.12.1 
busy-signal 1.4.3 
emmet 2.4.3 
highlight-selected 0.13.1 
intentions 1.1.5 
less-than-slash 0.17.0 
linter 2.2.0 
linter-ui-default 1.6.10 
pigments 0.40.2 
prettier-atom 0.41.0 
project-manager 3.3.5 
split-diff 1.5.1 
```

**Comment by mupchrch** [comment]
@jolebowski Are you still seeing this issue? I am not sure about the inner workings of atom's file writing module, but I can tell you that this package creates files in the `.atom` folder in your home directory for any temp text editors that it opens. Could there be something unique about how your system is configured that might be affecting this?

**Comment by mupchrch** [comment]
Closing as I am unable to reproduce and no response was received. Please reopen if you are still facing this issue, thanks!

**Comment by mrB0ndis** [comment]
```
/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:14
Hide Stack Trace
Error: Unable to watch path
    at HandleWatcher.start (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:14:10346)
    at new HandleWatcher (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:14:9365)
    at new PathWatcher (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:14:11211)
    at Object.e.watch (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:14:12631)
    at File.subscribeToNativeChangeEvents (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:14:1140850)
    at File.writeSync (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:14:1139544)
    at Object._createTempFiles (/home/mrb0nd/.atom/packages/split-diff/lib/split-diff.coffee:547:21)
    at Object.updateDiff (/home/mrb0nd/.atom/packages/split-diff/lib/split-diff.coffee:306:20)
    at /home/mrb0nd/.atom/packages/split-diff/lib/split-diff.coffee:447:10
    at Function.simpleDispatch (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:1215561)
    at TextBuffer.emitDidStopChangingEvent (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:504974)
    at later (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:14:104450)
```

**Comment by ionosphere** [comment]
Error: Unable to watch path
    at HandleWatcher.start (/usr/share/atom/resources/app/static/<embedded>:14:10346)
    at new HandleWatcher (/usr/share/atom/resources/app/static/<embedded>:14:9365)
    at new PathWatcher (/usr/share/atom/resources/app/static/<embedded>:14:11211)
    at Object.e.watch (/usr/share/atom/resources/app/static/<embedded>:14:12631)
    at File.subscribeToNativeChangeEvents (/usr/share/atom/resources/app/static/<embedded>:14:1140850)
    at File.writeSync (/usr/share/atom/resources/app/static/<embedded>:14:1139544)
    at Object._createTempFiles (/home/djoulin/.atom/packages/split-diff/lib/split-diff.coffee:543:21)
    at Object.updateDiff (/home/djoulin/.atom/packages/split-diff/lib/split-diff.coffee:306:20)
    at /home/djoulin/.atom/packages/split-diff/lib/split-diff.coffee:449:10
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1215561)
    at TextBuffer.emitDidStopChangingEvent (/usr/share/atom/resources/app/static/<embedded>:11:504974)
    at later (/usr/share/atom/resources/app/static/<embedded>:14:104450)
