### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by iainvdw** [mupchrch/split-diff#15]
1. Create split diff view with two editor panes
2. Close one editor pane without stopping split diff view

**Atom Version**: 1.5.0
**System**: Mac OS X 10.11
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package, v0.5.5

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:790

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:790:15)
    at TextEditorMarker.module.exports.TextEditorMarker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:179:33)
    at TextEditorMarker.module.exports.TextEditorMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:240:36)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.refreshMarkerScreenPositions (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker-layer.js:128:16)
    at DisplayBuffer.module.exports.DisplayBuffer.refreshMarkerScreenPositions (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1155:15)
    at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:315:14)
    at DisplayBuffer.module.exports.DisplayBuffer.updateWrappedScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:327:19)
    at DisplayBuffer.module.exports.DisplayBuffer.setSoftWrapped (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:472:14)
    at TextEditor.module.exports.TextEditor.setSoftWrapped (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2321:33)
    at DiffViewEditor.enableSoftWrap (/Users/Iain/.atom/packages/split-diff/lib/build-lines.js:122:18)
    at Object.module.exports.SplitDiff.disable (/Users/Iain/.atom/packages/split-diff/lib/split-diff.coffee:132:24)
    at /Users/Iain/.atom/packages/split-diff/lib/split-diff.coffee:97:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:254:27)
    at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:466:18)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:444:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:657:35)
    at Workspace.module.exports.Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:696:21)
    at atom-workspace.commandRegistry.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:170:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:22.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:20.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.4.0 split-diff:enable (atom-text-editor.editor)
     -0:12.8.0 core:copy (atom-text-editor.editor.is-focused)
     -0:11.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:06.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:05.9.0 refactor:done (atom-text-editor.editor.is-focused)
     -0:05.9.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:05.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.4.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".idea",
      ".cache",
      "node_modules",
      "php/vendor"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "one-dark-ui",
      "monokai-seti"
    ]
  },
  "split-diff": {
    "ignoreWhitespace": true
  }
}
```

### Installed Packages

```coffee
# User
auto-update-packages, v1.0.0
autoclose-html, v0.20.0
docblockr, v0.7.3
emmet, v2.4.1
file-types, v0.5.1
highlight-selected, v0.11.2
html-entities, v0.4.0
js-refactor, v0.6.0
language-api-blueprint, v1.0.2
language-svg, v0.9.0
linter, v1.11.3
minimap, v4.19.0
minimap-pigments, v0.1.7
monokai-seti, v0.7.0
php-integrator-annotations, v0.2.4
php-integrator-autocomplete-plus, v0.5.1
php-integrator-base, v0.5.3
php-integrator-navigation, v0.4.0
php-integrator-tooltips, v0.3.1
php-twig, v4.0.0
pigments, v0.23.1
refactor, v0.6.0
split-diff, v0.5.5
tool-bar, v0.2.0

# Dev
No dev packages
```

**Comment by mupchrch** [comment]
After looking into this a little bit, I believe this is actually a general atom bug. https://github.com/atom/atom/issues/10957

**Comment by mupchrch** [comment]
I believe this is fixed.
