### ISSUE TITLE
Uncaught TypeError: atom.grammars.languageModeForGrammarAndBuffer is not a function

### ISSUE THREAD

**Issue by bilbonotry** [mupchrch/split-diff#166]
[Enter steps to reproduce:]

1. Have several tabs opened
2. Type Ctrl-Shift-P to get atom command input
3. Select Split Diff: Toggle
(same error with Ctrl-Alt-D directly)

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.6
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package 1.6.0

### Stack Trace

Uncaught TypeError: atom.grammars.languageModeForGrammarAndBuffer is not a function

```
At /media/home/blaise/.atom/packages/split-diff/lib/split-diff.coffee:396

TypeError: atom.grammars.languageModeForGrammarAndBuffer is not a function
    at Object._getEditorsForQuickDiff (/packages/split-diff/lib/split-diff.coffee:396:57)
    at Object.diffPanes (/packages/split-diff/lib/split-diff.coffee:221:27)
    at Object.toggle (/packages/split-diff/lib/split-diff.coffee:94:8)
    at /packages/split-diff/lib/split-diff.coffee:82:32)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:143:35)
    at SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:327:26)
    at HTMLDivElement.core:confirm (/usr/share/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:84:20)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:24 intentions:highlight (input.hidden-input)
     -0:23.7.0 command-palette:toggle (input.hidden-input)
     -0:20.8.0 core:move-down (input.hidden-input)
     -0:20.4.0 core:confirm (input.hidden-input)
     -0:20.4.0 split-diff:toggle (input.hidden-input)
     -0:01.4.0 intentions:highlight (input.hidden-input)
     -0:01.3.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-java-decompiler 0.1.2 
atom-xmlvalidate 0.5.0 
busy-signal 2.0.1 
file-icons 2.1.24 
git-plus 8.1.0 
git-time-machine 2.1.0 
intentions 1.1.5 
language-ansible 0.2.2 
linter 2.3.0 
linter-ansible-linting 1.4.0 
linter-ansible-syntax 1.2.2 
linter-autocomplete-jing 0.8.4 
linter-shellcheck 1.6.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-cursorline 0.2.0 
print-code 0.7.1 
project-plus 1.0.0 
quantum-shell 0.7.1 
split-diff 1.6.0 
Sublime-Style-Column-Selection 1.7.5 
susave 0.4.0 
tab-switcher 1.5.6 
xml-formatter 0.13.0 
```

**Comment by mupchrch** [comment]
@bilbonotry is this still happening for you?

**Comment by mupchrch** [comment]
Closing for now, please reopen if this is still an issue. Thanks!
