### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by mzukiewicz** [mupchrch/split-diff#167]
[Steps to reproduce:]

1. Open a diff between to files.
2. Close one of the files.

[Different possibility:]
1. Open a diff between to files.
2. Delete one of the open files.
3. Close the diff

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package 1.6.0

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:519139)
    at TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:27540)
    at EditorDiffExtender._createLineMarker (/packages/split-diff/lib/editor-diff-extender.js:229:18)
    at EditorDiffExtender.selectLines (/packages/split-diff/lib/editor-diff-extender.js:142:14)
    at DiffView._selectChunk (/packages/split-diff/lib/diff-view.js:309:33)
    at DiffView.nextDiff (/packages/split-diff/lib/diff-view.js:108:24)
    at Object.nextDiff (/packages/split-diff/lib/split-diff.coffee:174:33)
    at /packages/split-diff/lib/split-diff.coffee:65:12)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:347598)
    at HTMLButtonElement.FooterView.nextDiffButton.onclick (/packages/split-diff/lib/ui/footer-view.coffee:26:21)
```

### Commands

```
     -1:13.3.0 git-time-machine:toggle (input.hidden-input)
     -0:53.8.0 core:copy (span.syntax--entity.syntax--other.syntax--attribute-name.syntax--class.syntax--html)
     -0:47.6.0 git-time-machine:toggle (input.hidden-input)
     -0:02.5.0 split-diff:next-diff (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.teletype-Authenticated)
```

### Non-Core Packages

```
duplicate-removal 0.1.3 
git-plus 8.7.1 
git-time-machine 2.1.0 
minimap 4.29.9 
minimap-split-diff 0.3.7 
print-code 0.7.1 
remote-ftp 2.2.2 
remote-sync 4.1.8 
split-diff 1.6.0 
teletype 0.13.4 
```

**Comment by mupchrch** [comment]
@mzukiewicz is this still happening for you?

**Comment by mupchrch** [comment]
Closing for now, please reopen if this is still an issue. Thanks!

**Comment by siteleas** [comment]
I just had it happen today. 

# Reproducing the Problem
I think I can re-produce the problem now. Here is what I did to create the problem:

1. While working on a file that is tracked in git, I hit Alt-T (opens git time machine)
2. then I click the timeline to a previous commit (opens the previous commit in split-view
3. I close the tab that showed the time machine version of the file
4. Auto-diff remains active even though the tab with the time machine version of the file was closed
5. Clicking anywhere in the current version of the file seems to fire this error for each click

## To Cause the Error to Stop Appearing
I was able to stop the error by toggling the split-diff feature `Ctrl-Alt-D`

*The split-diff feature should not be on after the git-time-machine tab is closed. Every time the user clicks, split-diff should check to see if the time-machine version of the file is still opening before trying to sync the views*

**If this comment is helpful to you, please click the like emoticon**
