### ISSUE TITLE
Installing “split-diff@1.6.1” failed

### ISSUE THREAD

**Issue by ploden** [mupchrch/split-diff#180]
Trying to install within 1.60.0 x64 on MacOS. Output:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
1 verbose cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/Users/ploden/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/Users/ploden/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/split-diff/versions/1.6.1/tarball',
1 verbose cli   '--target=9.4.4',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v12.14.1
4 verbose npm-session 9d5539f4a6751dbf
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 500 https://www.atom.io/api/packages/split-diff/versions/1.6.1/tarball 80685ms attempt #3
8 silly fetchPackageMetaData error for https://www.atom.io/api/packages/split-diff/versions/1.6.1/tarball 500 Internal Server Error - GET https://www.atom.io/api/packages/split-diff/versions/1.6.1/tarball
9 timing stage:rollbackFailedOptional Completed in 1ms 
10 timing stage:runTopLevelLifecycles Completed in 80705ms
11 verbose stack Error: 500 Internal Server Error - GET https://www.atom.io/api/packages/split-diff/versions/1.6.1/tarball
11 verbose stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:117:15
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:94:5)
12 verbose statusCode 500 
13 verbose pkgid https://www.atom.io/api/packages/split-diff/versions/1.6.1/tarball
14 verbose cwd /private/var/folders/9d/92wlvmk10cv1f6nv_g8cfj4m0000gn/T/apm-install-dir-2022318-32661-glh740.6ivo5
15 verbose Darwin 21.3.0
16 verbose argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/ploden/.atom/.apm/.apmrc" "--userconfig" "/Users/ploden/.atom/.apmrc" "install" "https://www.atom.io/api/packages/split-diff/versions/1.6.1/tarball" "--target=9.4.4" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
17 verbose node v12.14.1
18 verbose npm  v6.14.13
19 error code E500
20 error 500 Internal Server Error - GET https://www.atom.io/api/packages/split-diff/versions/1.6.1/tarball
21 verbose exit [ 1, true ]
```

**Comment by pw64** [comment]
The same for me. Atom 1.6.0 and split-diff 1.6.1.
Unable to install, after some time waiting to see the Install-clickable again. Nothing seems to have happened.
