### ISSUE TITLE
problem in install package

### ISSUE THREAD

**Issue by vahidsg** [mupchrch/split-diff#182]
try to install via " apm install split-diff"
TypeError: Cannot read property 'latest' of undefined
    at C:\Users\*\AppData\Local\atom\app-1.63.1\resources\app\apm\lib\instal
l.js:256:29
    at Request._callback (C:\Users\*\AppData\Local\atom\app-1.63.1\resources
\app\apm\lib\request.js:57:22)
    at Request.self.callback (C:\Users\*\AppData\Local\atom\app-1.63.1\resou
rces\app\apm\node_modules\←[4mrequest←[24m\request.js:185:22)
←[90m    at Request.emit (events.js:223:5)←[39m
    at Request.<anonymous> (C:\Users\*\AppData\Local\atom\app-1.63.1\resourc
es\app\apm\node_modules\←[4mrequest←[24m\request.js:1154:10)
←[90m    at Request.emit (events.js:223:5)←[39m
    at IncomingMessage.<anonymous> (C:\Users\*\AppData\Local\atom\app-1.63.1
\resources\app\apm\node_modules\←[4mrequest←[24m\request.js:1076:12)
←[90m    at Object.onceWrapper (events.js:312:28)←[39m
←[90m    at IncomingMessage.emit (events.js:228:7)←[39m
←[90m    at endReadableNT (_stream_readable.js:1185:12)←[39m

try install via " apm install https://github.com/mupchrch/split-diff.git "
Cloning https://github.com/mupchrch/split-diff.git failed
Installing modules done
Cannot read property 'getReferenceTarget' of null

**Comment by cbotsikas** [comment]
@vahidsg atom is deprecated. You can use https://github.com/pulsar-edit instead which is the community fork of Atom and install this plugin using ppm: `ppm install split-diff`

**Comment by Roko131** [comment]
You can just add the repo content into Atom package folder
