### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setScrollTop' of null

### ISSUE THREAD

**Issue by MikeLP** [mupchrch/split-diff#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package, v0.4.4

### Stack Trace

Uncaught TypeError: Cannot read property 'setScrollTop' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:315

TypeError: Cannot read property 'setScrollTop' of null
  at atom-text-editor.TextEditorElement.setScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:315:28)
  at TextEditor.module.exports.TextEditor.setScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2799:39)
  at SyncScroll._scrollPositionChanged (/Users/iyanello/.atom/packages/split-diff/lib/sync-scroll.js:46:19)
  at /Users/iyanello/.atom/packages/split-diff/lib/sync-scroll.js:29:22
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:105:47
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1028:29)
  at TextEditorPresenter.module.exports.TextEditorPresenter.commitPendingScrollTopPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:2056:14)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:110:12)
  at LinesYardstick.module.exports.LinesYardstick.prepareScreenRowsForMeasurement (/Applications/Atom.app/Contents/Resources/app.asar/src/lines-yardstick.js:24:63)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:183:27)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:196:38)
  at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:278:21)
  at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:929:16)
  at atom-text-editor.TextEditorElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:87:22)
  at atom-pane-container.module.exports.PaneContainerElement.rootChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container-element.js:38:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at PaneContainer.module.exports.PaneContainer.setRoot (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:165:20)
  at PaneContainer.module.exports.PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:175:19)
  at PaneAxis.module.exports.PaneAxis.reparentLastChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:219:19)
  at PaneAxis.module.exports.PaneAxis.removeChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:184:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:227:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at Pane.module.exports.Pane.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:641:20)
  at Pane.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:31:58)
  at Pane.module.exports.Pane.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:632:39)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:406:21)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:448:16)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
  4x -4:42.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 10x -4:15.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -4:04.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 23x -1:56.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:51.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 12x -1:03.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  4x -1:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:38.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  5x -0:35.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:33.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:33.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:22.5.0 split-diff:diffPanes (atom-text-editor.editor.is-focused)
     -0:17 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:16.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:15.8.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:15.8.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "atom-beautify"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.1
autocomplete-paths, v1.0.2
autocomplete-python, v0.9.4
color-picker, v2.0.13
emmet, v2.3.13
es-identifier-highlight, v0.2.7
language-rust, v0.4.5
linter, v1.10.0
linter-php, v1.0.5
pigments, v0.18.1
split-diff, v0.4.4

# Dev
No dev packages
```

**Comment by mupchrch** [comment]
Were you trying to use this package when this error happened? Or did this error happen randomly even though you thought split-diff was disabled?

**Comment by ferhtgoldaraz** [comment]
I hit this error, too. I was trying to diff something staged (as if I were to do `git diff --staged) so the new pane was empty. The error happened when I closed the empty pane.

**Comment by pistou** [comment]
I found a way to reproduce this each time:
Launch split-diff when you have only one file open ; it will try to diff with an empty file. Close the emplty file, it will then trigger this error.

Currently on 
Atom v1.1.0
WIndows 10

**Comment by mupchrch** [comment]
Thank you! Not sure how I missed that use case. Perhaps this is a sign that I should actually write tests..

Anyway, I don't really know why it is trying to sync the scrolls on close of an editor. There doesn't appear to be anything I can check on the editor objects to determine if they are valid to call setScrollTop() on. Therefore, I put a try/catch in that solves the problem.
