### ISSUE TITLE
Uncaught TypeError: SplitDiffCompute.computeCharDiff is not a function

### ISSUE THREAD

**Issue by pistou** [mupchrch/split-diff#22]
[Enter steps to reproduce below:]

1. Open two files on two panes
2. Ctrl + Shift + P -> Split Diff : Enable
3. Live modifiy one off the two files
4. This error is thrown on every change

**Atom Version**: 1.6.0
**System**: Unknown Windows Version
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package, v0.6.2

### Stack Trace

Uncaught TypeError: SplitDiffCompute.computeCharDiff is not a function

```
At /C:/Users/Pierre/.atom/packages/split-diff/lib/split-diff.coffee:323

TypeError: SplitDiffCompute.computeCharDiff is not a function
    at Object.<anonymous> (file:///C:/Users/Pierre/.atom/packages/split-diff/lib/split-diff.coffee:278:39)
    at Object.module.exports.SplitDiff.highlightCharDiff (file:///C:/Users/Pierre/.atom/packages/split-diff/lib/split-diff.coffee:277:9)
    at Object.module.exports.SplitDiff.updateDiff (file:///C:/Users/Pierre/.atom/packages/split-diff/lib/split-diff.coffee:125:8)
    at Object.module.exports.SplitDiff.diffPanes (file:///C:/Users/Pierre/.atom/packages/split-diff/lib/split-diff.coffee:103:6)
    at Object.module.exports.SplitDiff.toggle (file:///C:/Users/Pierre/.atom/packages/split-diff/lib/split-diff.coffee:295:8)
    at atom-workspace.subscriptions.add.atom.commands.add.split-diff:toggle (file:///C:/Users/Pierre/.atom/packages/split-diff/lib/split-diff.coffee:30:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Pierre\AppData\Local\atom\app-1.6.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Pierre\AppData\Local\atom\app-1.6.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Pierre\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Pierre\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\Pierre\AppData\Local\atom\app-1.6.0\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\Pierre\AppData\Local\atom\app-1.6.0\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:32 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:32 core:cancel (atom-text-editor.editor.is-focused)
     -0:29.7.0 core:undo (atom-text-editor.editor.is-focused)
     -0:29.2.0 core:redo (atom-text-editor.editor.is-focused)
     -0:27.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:27 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:26.4.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:22.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:17.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:15.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:15.1.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:12.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:03.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:02.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 split-diff:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "fileEncoding": "iso885915",
    "themes": [
      "flatland-dark-ui",
      "tomorrow-night-eighties-syntax"
    ]
  },
  "split-diff": {
    "ignoreWhitespace": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, vundefined
autocomplete-clang, v0.8.9
color-picker, v2.1.1
column-select, v0.2.0
emmet, v2.4.3
file-icons, v1.6.19
flatland-dark-ui, v0.2.4
minimap, v4.21.0
minimap-split-diff, v0.3.0
pigments, v0.26.0
pretty-json, v0.4.1
project-manager, v2.8.0
react, v0.14.2
split-diff, v0.6.2
tomorrow-night-eighties-syntax, v0.13.0

# Dev
No dev packages
```

**Comment by mupchrch** [comment]
This is startling. I did remove that function in the latest update, but I'm positive none of the code is calling it. The only thing I can guess is that somehow all of your split-diff files updated except for your main split-diff file, so it is still trying to call that now nonexistent function from the main file.

Would you mind deleting split-diff and re-downloading it? I have a feeling something went wrong with the package updater when you updated to the latest version. Let me know if that fixes the issue or if my assumption is way off.

**Comment by pistou** [comment]
Seems like it was an issue with the updater indeed :+1:
