### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clipScreenColumn' of undefined

### ISSUE THREAD

**Issue by chrismwendt** [mupchrch/split-diff#3]
I'm not sure if this is a split-diff bug or Atom bug. I got this error while diffing text with long lines.

![nov 09 2015 13 11](https://cloud.githubusercontent.com/assets/1387653/11046770/007a0830-86e4-11e5-8d41-9ecdd0d28570.gif)

0. Enter split diff view
0. Paste a long line of text to pane A (so that it wraps on a new line)
0. In pane B, insert a newline followed by the same line of text you put in pane A
0. The error should appear

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'clipScreenColumn' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:784

TypeError: Cannot read property 'clipScreenColumn' of undefined
  at DisplayBuffer.module.exports.DisplayBuffer.clipScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:784:55)
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:713:19)
  at DisplayBuffer.module.exports.DisplayBuffer.screenRangeForBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:646:20)
  at Marker.module.exports.Marker.getScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:139:33)
  at TextEditorPresenter.module.exports.TextEditorPresenter.fetchDecorations (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1597:48)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:116:14)
  at LinesYardstick.module.exports.LinesYardstick.prepareScreenRowsForMeasurement (/Applications/Atom.app/Contents/Resources/app.asar/src/lines-yardstick.js:24:63)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:183:27)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:196:38)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:298:28
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:174:9)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61

```

### Commands

```
     -0:30.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:29.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:28.5.0 core:select-all (atom-text-editor.editor)
     -0:28 core:backspace (atom-text-editor.editor)
     -0:26.4.0 core:select-all (atom-text-editor.editor)
  2x -0:26 core:backspace (atom-text-editor.editor)
     -0:23.4.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:20.3.0 tabs:split-left (li.tab.sortable.active.right-clicked)
     -0:15.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:13.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:12.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:10.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10.3.0 split-diff:diffPanes (atom-text-editor.editor)
     -0:04.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:03.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:03.3.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "autocomplete-emojis",
      "autocomplete-plus",
      "linter-rubocop",
      "vim-mode"
    ]
  },
  "editor": {
    "invisibles": {},
    "scrollPastEnd": true,
    "softWrap": true,
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
git-log, v0.4.1
language-haskell, v1.4.11
language-puppet, v0.15.0
language-terraform, v0.6.0
last-cursor-position, v0.9.0
linter, v1.8.1
linter-ruby, v1.2.0
minimap, v4.15.0
minimap-find-and-replace, v4.3.1
minimap-git-diff, v4.1.8
split-diff, v0.4.4
tasks, v2.4.0

# Dev
No dev packages
```

**Comment by mupchrch** [comment]
I wouldn't be surprised if this is me; I am doing some hacky stuff that sort of mimics soft wrap so that I can insert blank lines that don't affect line numbers.

I find it strange that this works fine when manually typing in the long lines, but breaks when pasting. I don't normally use soft wrap, but yeah this definitely seems like a bad bug if you do.
