### ISSUE TITLE
Uncaught Error: Cannot find module 'diff'

### ISSUE THREAD

**Issue by sshort** [mupchrch/split-diff#34]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.0
**System**: Mac OS X 10.11.4
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package, v0.7.3

### Stack Trace

Uncaught Error: Cannot find module 'diff'

```
At module.js:340

Error: Cannot find module 'diff'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Users/steve/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Users/steve/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at _computeDiffChunks (/Users/steve/.atom/packages/split-diff/lib/split-diff-compute.js:57:16)
    at Object.computeDiff (/Users/steve/.atom/packages/split-diff/lib/split-diff-compute.js:44:44)
    at Object.module.exports.SplitDiff.updateDiff (/Users/steve/.atom/packages/split-diff/lib/split-diff.coffee:165:37)
    at Object.module.exports.SplitDiff.diffPanes (/Users/steve/.atom/packages/split-diff/lib/split-diff.coffee:123:8)
    at Object.module.exports.SplitDiff.toggle (/Users/steve/.atom/packages/split-diff/lib/split-diff.coffee:387:8)
    at atom-workspace.subscriptions.add.atom.commands.add.split-diff:toggle (/Users/steve/.atom/packages/split-diff/lib/split-diff.coffee:32:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/steve/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Users/steve/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/steve/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Users/steve/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Users/steve/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -1:07.9.0 open-recent:Dir2-/Users/steve (atom-text-editor.editor.is-focused)
     -1:07.8.0 tree-view:toggle-focus (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-seti-ui)
     -1:00.7.0 tree-view:remove-project-folder (div.header.list-item)
     -0:58.2.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:39.7.0 open-recent:File1-/Users/steve/cws/apis/cws_policy_schema.json (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:14.6.0 split-diff:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.23
atom-alignment, v0.12.1
autoclose-html, v0.23.0
change-case, v0.6.0
event-kit, v2.0.0
highlight-selected, v0.11.2
language-scala, v1.1.6
linter, v1.11.4
linter-htmlhint, v1.1.2
linter-js-yaml, v1.2.5
linter-jshint, v2.1.0
linter-swagger, v0.3.6
minimap, v4.21.0
minimap-split-diff, v0.3.0
open-recent, v5.0.0
seti-ui, v0.9.2
split-diff, v0.7.3

# Dev
No dev packages
```

**Comment by mupchrch** [comment]
I would wager the package upgrader/installer messed up yet again. You can try two things.

First, you could try uninstalling and reinstalling. If you don't want to do this then try the next option.

The second option is slightly more involved. You would open the package in Settings View and click the "view code" button. Then you would run `Update Package Dependencies: Update` from the command palette.

If these don't work then could you let me know what is in your "node_modules" folder when you are in the package (by hitting the "view code" button).

**Comment by mupchrch** [comment]
Closing this since it seems to be a one off and could possibly be fixed for the user. Please feel free to reopen with any additional info!

**Comment by sshort** [comment]
Sorry for delay replying.  I have removed and reinstalled and split-diff is now working fine.

Thanks
Steve

**Comment by mupchrch** [comment]
Good to hear! Thanks
