### ISSUE TITLE
Uncaught Error: Cannot find module './split-diff-compute'

### ISSUE THREAD

**Issue by patrick-armitage** [mupchrch/split-diff#38]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.10.5
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package, v0.7.5

### Stack Trace

Uncaught Error: Cannot find module './split-diff-compute'

```
At module.js:340

Error: Cannot find module './split-diff-compute'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.SplitDiff.updateDiff (/Users/paa/.atom/packages/split-diff/lib/split-diff.coffee:9:3)
    at Object.module.exports.SplitDiff.diffPanes (/Users/paa/.atom/packages/split-diff/lib/split-diff.coffee:128:59)
    at atom-workspace.subscriptions.add.atom.commands.add.split-diff:enable (/Users/paa/.atom/packages/split-diff/lib/split-diff.coffee:29:5)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:16.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:14.4.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -1:12.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:53.6.0 core:move-right (atom-text-editor.editor.is-focused)
  8x -0:53.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:51.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:51.3.0 core:move-left (atom-text-editor.editor.is-focused)
 10x -0:49.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:05.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:05.5.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  9x -0:04.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  4x -0:03.2.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  3x -0:02.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.7.0 split-diff:enable (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "atom-lint",
      "atom-lint",
      "atom-lint",
      "file-watcher",
      "nuclide-file-watcher",
      "linter-python-pep257",
      "python-indent",
      "save-session"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7
atom-pair, v2.0.10
build-make, v0.9.0
cucumber, v0.5.0
formatter, v2.12.3
git-tab-status, v1.9.2
language-diff, v0.4.0
language-gherkin, v1.0.3
language-haml, v0.24.0
language-x86asm, v0.8.0
linter, v1.11.4
linter-clang, v3.4.4
linter-cpplint, v1.0.1
linter-gcc, v0.6.12
linter-pep8, v1.2.1
linter-python-pep8, v0.2.0
linter-python-pyflakes, v0.1.0
linter-rubocop, v0.4.7
merge-conflicts, v1.4.2
minimap-split-diff, v0.3.0
monokai, v0.18.0
pain-split, v1.4.0
pretty-json, v1.0.3
rubocop-auto-correct, v1.2.0
ruby-slim, v0.2.0
split-diff, v0.7.5
ssh-config, v0.10.1
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by mupchrch** [comment]
Seems like your update may have failed - one of the split diff files is from an older version. To fix this, I think the easiest thing for you to do is uninstall and then reinstall unfortunately. Let me know if that doesn't work!

**Comment by chrislp** [comment]
Restarting Atom fixed it for me.
