### ISSUE TITLE
Uncaught TypeError: projectRepo.repo.getHeadBlob is not a function

### ISSUE THREAD

**Issue by mackelito** [mupchrch/split-diff#43]
[Enter steps to reproduce below:]

1. Enable diff

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package, v0.7.5

### Stack Trace

Uncaught TypeError: projectRepo.repo.getHeadBlob is not a function

```
At /Users/markus/.atom/packages/split-diff/lib/split-diff.coffee:292

TypeError: projectRepo.repo.getHeadBlob is not a function
    at Object.module.exports.SplitDiff._setupGitRepo (/Users/markus/.atom/packages/split-diff/lib/split-diff.coffee:292:44)
    at Object.module.exports.SplitDiff._getVisibleEditors (/Users/markus/.atom/packages/split-diff/lib/split-diff.coffee:259:6)
    at Object.module.exports.SplitDiff.diffPanes (/Users/markus/.atom/packages/split-diff/lib/split-diff.coffee:119:16)
    at atom-workspace.subscriptions.add.atom.commands.add.split-diff:enable (/Users/markus/.atom/packages/split-diff/lib/split-diff.coffee:32:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:51.2.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-an-old-hope-syntax.theme-one-dark-ui)
     -0:48.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:48.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:43.1.0 pane:show-next-recently-used-item (atom-text-editor.editor.is-focused)
     -0:43 pane:move-active-item-to-top-of-stack (atom-text-editor.editor.is-focused)
     -0:32.5.0 core:paste (atom-text-editor.editor.is-focused)
  5x -0:30.2.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-an-old-hope-syntax.theme-one-dark-ui)
     -0:09.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:07.2.0 split-diff:prev-diff (atom-text-editor.editor)
     -0:06.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:06.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:04.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 split-diff:enable (atom-text-editor.editor)
     -0:01.1.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-an-old-hope-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "php-debug",
      "terminal-plus",
      "atom-typescript",
      "atom-ternjs",
      "atom-css-comb"
    ],
    "ignoredNames": [
      "htdocs/media/js",
      "htdocs/media/css",
      "htdocs/var/cache"
    ],
    "themes": [
      "one-dark-ui",
      "an-old-hope-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
an-old-hope-syntax, v0.5.0
angularjs-styleguide-snippets, v0.7.3
atom-alignment, v0.12.1
atom-hg, v2.0.4
auto-reveal-in-sidebar, v0.8.0
autoclose-html, v0.23.0
autocomplete-angular-material, v0.4.0
bottom-dock, v0.4.4
css-comb, v2.4.3
editorconfig, v1.4.1
file-icons, v1.7.11
file-types, v0.5.1
linter, v1.11.4
linter-csslint, v1.3.2
linter-htmlhint, v1.1.4
linter-jshint, v2.1.0
linter-manager, v0.2.12
linter-scss-lint, v3.0.3
merge-conflicts, v1.4.2
minimap, v4.23.5
pigments, v0.26.2
project-manager, v2.9.7
split-diff, v0.7.5
sync-settings, v0.7.2
todo-manager, v0.2.8

# Dev
No dev packages
```

**Comment by mupchrch** [comment]
Hi, were you diffing a file that is part of a git repo? I think I have a fix for this anyway, but I am just curious. Thanks.

**Comment by mackelito** [comment]
Nope.. A mercurial repo 😜
