### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by EranGoldman** [mupchrch/split-diff#49]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Ubuntu 16.04
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package, v0.8.3

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/marinetech/.atom/packages/split-diff/lib/build-lines.js:111

TypeError: Cannot read property 'length' of undefined
    at DiffViewEditor.setWordHighlights (/home/marinetech/.atom/packages/split-diff/lib/build-lines.js:111:112)
    at Object.<anonymous> (/home/marinetech/.atom/packages/split-diff/lib/split-diff.coffee:503:30)
    at Object.module.exports.SplitDiff._highlightWordDiff (/home/marinetech/.atom/packages/split-diff/lib/split-diff.coffee:499:9)
    at Object.module.exports.SplitDiff._resumeUpdateDiff (/home/marinetech/.atom/packages/split-diff/lib/split-diff.coffee:245:8)
    at /home/marinetech/.atom/packages/split-diff/lib/split-diff.coffee:229:10
    at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:215:47)
    at /opt/atom/resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -4:55.9.0 platformio-ide:maintenance.serial-monitor (atom-text-editor.editor)
     -4:54.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -4:54.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -4:48.4.0 application:show-settings (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:43.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
 13x -4:40.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:11.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
  4x -4:08.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:30.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:10.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -3:09.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:44.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:31.4.0 tree-view:move (span.name.icon.icon-file-text)
     -1:28 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11.5.0 split-diff:toggle (atom-text-editor.editor.is-focused)
  2x -0:01.3.0 core:delete (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.9.3
build, v0.63.0
language-ini, v1.16.0
linter, v1.11.4
linter-gcc, v0.6.14
minimap-split-diff, v0.3.0
platformio-ide, v1.2.2
platformio-ide-terminal, v2.0.9
split-diff, v0.8.3
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by mupchrch** [comment]
Does split-diff break after this error or does it seem to keep working? Is the file you were trying to diff in a repository? Thanks!

**Comment by bfrederick** [comment]
I've also run into this issue.  The only Atom plugin I have installed is split-diff.  No git repo, just two local files.  The diff does not continue, no contents are shown on the new editor pane that appears.

**Comment by mupchrch** [comment]
@bfrederick Thanks for the info, I will bump this up on my priority list.
