### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined" when closing the split diff editor

### ISSUE THREAD

**Issue by Proteo** [mupchrch/split-diff#70]
Every time I close the split diff editor I get the following error:

`Uncaught TypeError: Cannot read property 'dispose' of undefined.`

![screen shot 2016-09-17 at 6 59 39 p m](https://cloud.githubusercontent.com/assets/376077/18611515/3c331c88-7d09-11e6-928e-ce665a725d8a.png)

I assume that because of this, the bar created at the bottom (the one with buttons and options) won't disappear from the editor even after closing the file:

![screen-shot-2016-09-17-at-7 13 01-p m](https://cloud.githubusercontent.com/assets/376077/18611574/3c46abf2-7d0b-11e6-81bf-01f998efc9e1.png)

I have to make a full restart to get ride of it.

Steps to reproduce:

1. ... Open (first-time toggle) the split diff
2. ... Close (second-time toggle) the split diff

**Atom Version**: 1.11.0-beta5
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package, v1.0.4

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25

TypeError: Cannot read property 'dispose' of undefined
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25:28
    at Set.forEach (native)
    at CompositeDisposable.module.exports.CompositeDisposable.dispose (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24:26)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/workspace.js:267:36
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:529:27)
    at TextEditor.module.exports.Model.destroy (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroyed (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:866:16)
    at Pane.module.exports.Model.destroy (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroy (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:851:39)
    at DiffViewEditor.cleanUp (/Users/proteo/.atom/packages/split-diff/lib/build-lines.js:177:18)
    at Object.module.exports.SplitDiff.disable (/Users/proteo/.atom/packages/split-diff/lib/split-diff.coffee:85:26)
    at Object.module.exports.SplitDiff.toggle (/Users/proteo/.atom/packages/split-diff/lib/split-diff.coffee:61:8)
    at atom-workspace.subscriptions.add.atom.commands.add.split-diff:toggle (/Users/proteo/.atom/packages/split-diff/lib/split-diff.coffee:51:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at executeCallback (/Users/proteo/.atom/packages/tool-bar/lib/tool-bar-button-view.js:105:19)
    at ToolBarButtonView._onClick (/Users/proteo/.atom/packages/tool-bar/lib/tool-bar-button-view.js:69:7)
```

### Commands

```
  6x -4:06.8.0 split-diff:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:19.2.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:10 split-diff:toggle (atom-text-editor.editor.is-focused)
  4x -1:05.1.0 split-diff:next-diff (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-proteo-dark-theme.theme-one-dark-ui)
     -0:47.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:45.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:31.1.0 core:close (atom-text-editor.editor.is-focused)
     -0:24.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:24.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:23.9.0 core:close (atom-text-editor.editor.is-focused)
     -0:18.5.0 split-diff:toggle (atom-text-editor.editor.is-focused)
  3x -0:12.9.0 split-diff:next-diff (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-proteo-dark-theme.theme-one-dark-ui)
  2x -0:07.1.0 split-diff:prev-diff (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-proteo-dark-theme.theme-one-dark-ui)
     -0:04.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:00.0 split-diff:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tool-bar-atom",
      "toolbar-iconshortcuts",
      "tool-bar-main"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".vscode",
      "*.sublime-project",
      "*.sublime-workspace",
      ".DS_Store",
      "._*",
      "Thumbs.db"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "tool-bar"
    ],
    "projectHome": "/Users/proteo/Sites",
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "proteo-dark-theme"
    ]
  },
  "split-diff": {
    "syncHorizontalScroll": true
  }
}
```

### Installed Packages

```coffee
# User
ample-syntax, v0.3.0 (inactive)
atom-beautify, v0.29.12 (active)
atom-drupal-api, v1.0.1 (inactive)
atom-icons, v0.2.2 (active)
atom-minify, v0.7.5 (active)
calexico-syntax, v0.4.0 (inactive)
caniuse, v0.9.0 (active)
docker, v0.7.0 (inactive)
drupal, v1.8.0 (active)
editorconfig, v1.4.1 (active)
lample-syntax, v0.1.1 (inactive)
language-docker, v1.1.7 (active)
leche-syntax, v3.0.0 (inactive)
linter, v1.11.16 (active)
linter-less, v2.6.0 (active)
linter-php, v1.2.0 (active)
native-color-picker, v0.2.0 (inactive)
project-manager, v3.2.3 (active)
proteo-dark-theme, v1.0.0 (active)
reference-theme, v0.0.0 (inactive)
split-diff, v1.0.4 (active)
tool-bar, v1.0.1 (active)
tool-bar-atom, v1.6.3 (inactive)
tool-bar-config, v0.1.0 (active)
tool-bar-main, v0.0.9 (inactive)
toolbar-iconshortcuts, v2.9.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Proteo** [comment]
I just noticed that this won't happen when switching to the stable version.

**Comment by mupchrch** [comment]
Thanks for the heads up, I've just logged an issue for this against the tabs package: https://github.com/atom/tabs/issues/377

It seems like a generic issue, since split-diff is just using the Atom API to create the new tabs. I don't use the beta though, so good catch!

**Comment by Proteo** [comment]
You're welcome mupchrch, best regards.
