### ISSUE TITLE
Uncaught TypeError: Arguments to CompositeDisposable must have a .dispose() method

### ISSUE THREAD

**Issue by henrydaehnke** [mupchrch/split-diff#74]
Here's the stack trace after issuing "Toggle" command with two .css files open:

1. Opened two .css files.
2. Called up command window: Ctrl-Shift-P
3. Typed in "Toggle" and selected "Split Diff: Toggle" from drop down.

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package, v1.0.5

### Stack Trace

Uncaught TypeError: Arguments to CompositeDisposable.add must have a .dispose() method

```
At C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:70

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:43:11)
    at new CompositeDisposable (C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:19:14)
    at C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\src\workspace.js:265:29
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\src\pane-container.js:388:27)
    at C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\src\pane-container.js:372:28
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at Pane.module.exports.Pane.addItem (C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\src\pane.js:491:20)
    at Object.module.exports.SplitDiff._getVisibleEditors (file:///C:/Users/<username>/.atom/packages/split-diff/lib/split-diff.coffee:339:17)
    at Object.module.exports.SplitDiff.diffPanes (file:///C:/Users/<username>/.atom/packages/split-diff/lib/split-diff.coffee:183:16)
    at Object.module.exports.SplitDiff.toggle (file:///C:/Users/<username>/.atom/packages/split-diff/lib/split-diff.coffee:63:8)
    at atom-workspace.subscriptions.add.atom.commands.add.split-diff:toggle (file:///C:/Users/<username>/.atom/packages/split-diff/lib/split-diff.coffee:51:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-li.<anonymous> (C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:139:19)
    at HTMLOListElement.jQuery.event.dispatch (C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (C:\Users\<username>\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -5:09.1.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -5:01.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 15x -4:58.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:50 core:confirm (atom-text-editor.editor.mini.is-focused)
 20x -4:25.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:16 find-and-replace:show (atom-text-editor.editor.is-focused)
     -3:13.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:57.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -1:52.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:50 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
 13x -1:31.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:36 core:copy (atom-text-editor.editor.is-focused)
     -0:34.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  4x -0:29.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:23.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:14 split-diff:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  },
  "split-diff": {
    "ignoreWhitespace": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined (inactive)
atom-beautify, v0.29.13 (inactive)
atom-typescript, v10.1.8 (active)
linter, v1.11.4 (active)
pumpkin-syntax, v0.1.0 (inactive)
split-diff, v1.0.5 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by mupchrch** [comment]
This boils down to the same issue as #74

Sorry you are experiencing this, I am actively looking into it 😞

**Comment by henrydaehnke** [comment]
No problem! And thanks for working on it. 

Sorry I didn't see the original issue #72.
