### ISSUE TITLE
Uncaught TypeError: Arguments to CompositeDisposable.add must have a .dispose() method

### ISSUE THREAD

**Issue by Spy-Seth** [mupchrch/split-diff#75]
[Enter steps to reproduce below:]

1. Opening the diff pane with the `Split diff: Toggle` command

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package, v1.0.5

### Stack Trace

Uncaught TypeError: Arguments to CompositeDisposable.add must have a .dispose() method

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
  at assertDisposable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
  at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
  at new CompositeDisposable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:19:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:265:29
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:388:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:372:28
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:491:20)
  at Object.module.exports.SplitDiff._getVisibleEditors (/Users/spy-seth/.atom/packages/split-diff/lib/split-diff.coffee:339:17)
  at Object.module.exports.SplitDiff.diffPanes (/Users/spy-seth/.atom/packages/split-diff/lib/split-diff.coffee:183:16)
  at Object.module.exports.SplitDiff.toggle (/Users/spy-seth/.atom/packages/split-diff/lib/split-diff.coffee:63:8)
  at atom-workspace.subscriptions.add.atom.commands.add.split-diff:toggle (/Users/spy-seth/.atom/packages/split-diff/lib/split-diff.coffee:51:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:114:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by Spy-Seth** [comment]
Duplicate of https://github.com/mupchrch/split-diff/issues/72
