### ISSUE TITLE
Uncaught TypeError: this._editor.displayBuffer.updateAllScreenLines is not a function

### ISSUE THREAD

**Issue by nico78** [mupchrch/split-diff#80]
[Enter steps to reproduce below:]

1. launch split diff via menu

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Linux Mint
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package, v1.0.6

### Stack Trace

Uncaught TypeError: this._editor.displayBuffer.updateAllScreenLines is not a function

```
At /home/nic/.atom/packages/split-diff/lib/build-lines.js:57

TypeError: this._editor.displayBuffer.updateAllScreenLines is not a function
    at DiffViewEditor.removeLineOffsets (/home/nic/.atom/packages/split-diff/lib/build-lines.js:57:32)
    at Object.module.exports.SplitDiff.clearDiff (/home/nic/.atom/packages/split-diff/lib/split-diff.coffee:221:24)
    at Object.module.exports.SplitDiff.updateDiff (/home/nic/.atom/packages/split-diff/lib/split-diff.coffee:145:6)
    at /home/nic/.atom/packages/split-diff/lib/split-diff.coffee:92:8
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1427:25
```

### Commands

```
     -0:20.9.0 intentions:highlight (atom-text-editor.editor.is-focused)
     -0:20.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:20.4.0 core:paste (atom-text-editor.editor.is-focused)
     -0:00.8.0 intentions:highlight (atom-text-editor.editor.is-focused)
     -0:00.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:00.4.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "formatter-json"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "split-diff": {}
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.76 (active)
eclipse-keybindings, v0.9.0 (active)
Ensime, v0.39.0 (active)
expand-region, v0.2.5 (inactive)
formatter-json, v1.0.1 (inactive)
git-line, v0.5.0 (inactive)
hyperclick, v0.0.39 (active)
intentions, v1.1.2 (active)
language-scala, v1.1.8 (active)
lines, v0.13.1 (inactive)
linter, v1.11.18 (active)
pretty-json, v1.6.1 (active)
sort-lines, v0.14.0 (inactive)
split-diff, v1.0.6 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by mupchrch** [comment]
I am baffled. The function `DiffViewEditor.removeLineOffsets` hasn't existed for months. You appear to have the latest version, so I am really unsure how this happened. Could be an issue with the Atom package installer. 

Did you just install this package? Or did you upgrade from a previous version of the package?

To fix your problem, you could try uninstalling split-diff and reinstalling.

**Comment by nico78** [comment]
hmm, yeah i upgraded recently from an old version. Sounds plausible - ok will try that - thanks

**Comment by nico78** [comment]
ok, works now - think there may have been another instance running with the old version - thanks for looking at for a great tool!

**Comment by mupchrch** [comment]
Awesome, glad your problem is resolved!
