### ISSUE TITLE
The version 1.1.2 has a bug

### ISSUE THREAD

**Issue by geovanisouza92** [mupchrch/split-diff#92]
Steps to reproduce below:

1. Update to 1.1.2
2. Put two files, side-by-side and try to enable diff

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package, v1.1.2

### Stack Trace

Uncaught TypeError: this._lineMarkerLayer.clear is not a function

```
At /home/geovani/.atom/packages/split-diff/lib/editor-diff-extender.js:106

TypeError: this._lineMarkerLayer.clear is not a function
    at EditorDiffExtender.destroyMarkers (/home/geovani/.atom/packages/split-diff/lib/editor-diff-extender.js:106:27)
    at DiffView.clearDiff (/home/geovani/.atom/packages/split-diff/lib/diff-view.js:79:31)
    at Object._resumeUpdateDiff (/home/geovani/.atom/packages/split-diff/lib/split-diff.coffee:245:15)
    at /home/geovani/.atom/packages/split-diff/lib/split-diff.coffee:231:8
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:173:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
     -0:07.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-electron-highlighter-syntax.theme-one-dark-ui)
     -0:01.0 command-palette:toggle (input.hidden-input)
     -0:00.2.0 core:confirm (input.hidden-input)
     -0:00.2.0 split-diff:toggle (input.hidden-input)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "autocomplete-atom-api",
      "deprecation-cop",
      "exception-reporting",
      "language-clojure",
      "language-csharp",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-property-list",
      "language-sass",
      "link",
      "markdown-preview",
      "metrics",
      "open-on-github",
      "package-generator",
      "styleguide",
      "vim-mode",
      "synced-sidebar",
      "activate-power-mode",
      "language-php",
      "pretty-json",
      "atom-grammar-test",
      "spell-check",
      "linter-rubocop",
      "whitespace",
      "language-ejs",
      "atom-easy-jsdoc",
      "react",
      "linter-eslint",
      "hyperclick"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "node_modules"
    ],
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "electron-highlighter-syntax"
    ],
    "warnOnLargeFileLimit": 1
  },
  "split-diff": {
    "ignoreWhitespace": true,
    "syncHorizontalScroll": true
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.2.0 (inactive)
atom-beautify, v0.29.17 (inactive)
atom-easy-jsdoc, v4.10.0 (inactive)
atom-material-syntax, v1.0.2 (inactive)
ctrl-dir-scroll, v0.2.2 (inactive)
editorconfig, v2.2.0 (active)
electron-highlighter-syntax, v1.7.0 (active)
emmet, v2.4.3 (active)
file-icons, v2.0.15 (active)
go-debug, v1.0.4 (active)
go-plus, v5.1.1 (active)
go-signature-statusbar, v1.2.0 (active)
hclfmt, v1.1.0 (active)
highlight-selected, v0.12.0 (active)
hyperclick, v0.0.40 (inactive)
language-diff, v0.7.0 (active)
language-ejs, v0.4.0 (inactive)
language-hcl, v0.4.0 (active)
linter, v1.11.21 (active)
linter-eslint, v8.1.0 (inactive)
linter-js-standard, v3.8.0 (active)
linter-jsonlint, v1.3.0 (active)
linter-rubocop, v0.5.3 (inactive)
nyancat, v0.12.0 (active)
pretty-json, v1.6.1 (inactive)
react, v0.16.2 (inactive)
sort-lines, v0.14.0 (inactive)
split-diff, v1.1.2 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (inactive)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (inactive)
metrics, v1.1.3 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

![Screenshot](https://lh3.googleusercontent.com/l9hrzDjCSMJY9yK0JkqyThXAVkeUulLHnxU6i1p_pmOeLIQbKTy_zYCciKr4ygLwR_QHjiqd3WDn8ZDwywUmv2qyZZwmouVsZQ94J5LbNx4x_P0-IQAsNqbQLi0jBa2USeO_MJa1QjZtXe_TjQl5fR3_yaycgw-zGsPMcwDaJarQAxdZ2ctYkiQuF0ofyQAYyPwNV8HyZZ6abjTt3FJRJhJgCO9Nhcovcn1Bh-7SnIvUPQen4YZhmqFEg8i04h7QmUXGkacgcfOzMD4wvK3Yku88SV_UQHPwJ3H3iOg0W_ivv8pknKaXP9L8YGyaHrkrdlqMVsq6w0MGURm3DxAfcpJjgKSeMr_76iIAtOLoip-CffcAzo02WVsdBzKb4BV8p-x4ocjWg26ydZINFqyzgib7t29XIIR9KA7LinM4QK7hmCUax0PjUZjN0oKvmxpQv_jfGqw802xc_HPjBOMg7R6ONoM1V4UQzVQgUqFUn7Ur457xtgd67PfuNJoV-9xuFpYtJZgGN0nQXUmqxlxlrvugFUHozSPY0x5NI0a5-5rbyXpHJQH-PsSDSJS2nrlSjlvOpDeix9x6IxmN-F0HuRJzfw6xurWDx_0HF1eEmAvXNPLmGPA7Ig=w476-h484-no)

**Comment by mupchrch** [comment]
Ugh so looks like Atom v1.13 has a bug with MarkerLayers that is causing this. I developed this on v1.14, but I wrongfully assumed it would work fine with v1.13. That is my bad. I think what I'm going to try to do is unpublish split-diff v1.1.2 and send out an update that is scoped to v1.14 and up.

So @geovanisouza92  you'll either need to just update your version of Atom, or rollback to the previous version of split-diff. To do that run `apm install split-diff@1.1.1` in your console while Atom is closed.

**Comment by geovanisouza92** [comment]
I've confirmed that it's working now. Thanks!
