### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by RJDUHA** [mupchrch/split-diff#93]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package 1.2.0

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Users/rjduha/.atom/packages/mupchrch-split-diff-a7d9805/lib/diff-view.js:236

TypeError: Cannot read property '0' of null
    at DiffView._selectChunk (/packages/mupchrch-split-diff-a7d9805/lib/diff-view.js:236:33)
    at DiffView.nextDiff (/packages/mupchrch-split-diff-a7d9805/lib/diff-view.js:96:10)
    at Object.nextDiff (/packages/mupchrch-split-diff-a7d9805/lib/split-diff.coffee:109:33)
    at /packages/mupchrch-split-diff-a7d9805/lib/split-diff.coffee:30:12)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1164:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:29.2.0 split-diff:toggle (input.hidden-input)
     -3:24.4.0 core:select-all (input.hidden-input)
     -3:24 core:copy (input.hidden-input)
     -3:22.4.0 core:select-all (input.hidden-input)
     -3:21.3.0 core:paste (input.hidden-input)
  3x -3:07.0 core:backspace (input.hidden-input)
     -3:05.4.0 core:move-down (input.hidden-input)
     -3:05.0 core:backspace (input.hidden-input)
     -2:55.2.0 split-diff:next-diff (input.hidden-input)
```

### Non-Core Packages

```
compare-files 0.8.0 
minimap-split-diff 0.3.6 
split-diff 1.2.0 
split-diff 1.2.0 
```

**Comment by mupchrch** [comment]
Hi @RJDUHA, any idea how to reproduce this issue?
